version: "3.9"
  
services: 
  rag_app:
    build:
        context: backend/python/
        dockerfile: rag_app/app/Dockerfile
    env_file: backend/python/rag_app/app/.env.local
    ports: 
        - '9876:9876'         
    networks:
        - myAppNetwork

  pgsql:
    build:
        context: backend/database/PostgreSQL/docker/
        dockerfile: Dockerfile
    env_file: backend/database/PostgreSQL/docker/.env
    ports: 
        - '5321:5432'        
    volumes: 
        - ./backend/database/PostgreSQL/docker/volumes/postgresql_data:/var/lib/postgresql/data
    networks:
        - myAppNetwork

  qdrant_db:
    build:
        context: backend/database/qdrant/docker/
        dockerfile: Dockerfile
    env_file: backend/database/qdrant/docker/.env.local
    ports: 
        - "6333:6333"
        - "6334:6334"   
    volumes:
      - ./backend/database/qdrant/docker/volumes/qdrant_data:/qdrant/storage
    networks:
        - myAppNetwork

networks:
    myAppNetwork:
        driver: bridge
  